A,B,C=input().split()
A=float(A)
B=float(B)
C=float(C)
pi=3.14159
a=float(.5*A*C)
b=float(pi*C*C)
c=float(.5*(A+B)*C)
d=float(B*B)
e=float(A*B)
print("TRIANGULO: {:.3f}".format(a))
print("CIRCULO: {:.3f}".format(b))
print("TRAPEZIO: {:.3f}".format(c))
print("QUADRADO: {:.3f}".format(d))
print("RETANGULO: {:.3f}".format(e))